// Code generated by "stringer -type=AnyCalendarKind"; DO NOT EDIT.

package datetime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Iso-0]
	_ = x[Gregorian-1]
	_ = x[Buddhist-2]
	_ = x[Japanese-3]
	_ = x[JapaneseExtended-4]
	_ = x[Ethiopian-5]
	_ = x[EthiopianAmeteAlem-6]
	_ = x[Indian-7]
	_ = x[Coptic-8]
	_ = x[Dangi-9]
	_ = x[Chinese-10]
	_ = x[Hebrew-11]
	_ = x[IslamicCivil-12]
	_ = x[IslamicObservational-13]
	_ = x[IslamicTabular-14]
	_ = x[IslamicUmmAlQura-15]
	_ = x[Persian-16]
	_ = x[Roc-17]
}

const _AnyCalendarKind_name = "IsoGregorianBuddhistJapaneseJapaneseExtendedEthiopianEthiopianAmeteAlemIndianCopticDangiChineseHebrewIslamicCivilIslamicObservationalIslamicTabularIslamicUmmAlQuraPersianRoc"

var _AnyCalendarKind_index = [...]uint8{0, 3, 12, 20, 28, 44, 53, 71, 77, 83, 88, 95, 101, 113, 133, 147, 163, 170, 173}

func (i AnyCalendarKind) String() string {
	if i < 0 || i >= AnyCalendarKind(len(_AnyCalendarKind_index)-1) {
		return "AnyCalendarKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AnyCalendarKind_name[_AnyCalendarKind_index[i]:_AnyCalendarKind_index[i+1]]
}
