name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Check versions
      run: |
        go version
        rustc --version

    - name: Build project
      run: |
        make all

    - name: Pre Upload artifacts
      run: |
        mv target/release/libicu_capi.a ./
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: c-libraries-${{ matrix.os }}-${{ runner.arch }}
        path: |
          icu4x
          *.a

